apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ai-news
spec:
  schedule: "0 8 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-news
            image: rio05docker/ai_news_server:stateful_arm_2020-12-16
            resources:
                limits:
                    memory: "1Gi"
                    cpu: "1"
                requests:
                    cpu: "100m"
                    memory: "30Mi"
            env:
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegramcredentials
                    key: TELEGRAM_BOT_TOKEN
              - name: TELEGRAM_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegramcredentials
                    key: TELEGRAM_CHAT_ID
            args:
            - python3
            - stateful_news_ai.py
          restartPolicy: OnFailure
