name: ai_news_server

on:
  push: # Trigger when push on develop branch
   branches:
      - develop
        
jobs:
  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.4
        with:
          version: latest
      
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - 
        name: Login to GitHub Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Dynamically set MY_DATE environment variable
        run: echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
            
      #Build&Push 
      -
        name: Build and push stateless version #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/ai_news_server:stateless_arm_${{ env.MY_DATE }} \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --file ./stateless/Dockerfile \
            ./stateless
      
      -
        name: Build and push stateful version #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/ai_news_server:stateful_arm_${{ env.MY_DATE }} \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --file ./src/inference/Dockerfile \
            ./src/inference
      
      -
        name: Build and push Telegram feedback server #see: https://github.com/marketplace/actions/docker-buildx
        run: |
          docker buildx build \
            --tag rio05docker/ai_news_server:telegram_arm_${{ env.MY_DATE }} \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --file ./src/feedback_server/Dockerfile \
            ./src/feedback_server
